<?php

/**
 * @file
 * Contains assignments.module.
 */

use Drupal\Core\Url;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function assignments_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the assignments module.
    case 'help.page.assignments':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('assignments') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function assignments_theme() {
  $theme = [];
  $theme['assignment'] = [
    'render element' => 'elements',
    'file' => 'assignment.page.inc',
    'template' => 'assignment',
  ];
  $theme['assignment_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'assignment.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function assignments_theme_suggestions_assignment(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#assignment'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'assignment__' . $sanitized_view_mode;
  $suggestions[] = 'assignment__' . $entity->bundle();
  $suggestions[] = 'assignment__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'assignment__' . $entity->id();
  $suggestions[] = 'assignment__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

/**
 *
 */
function assignments_preprocess_entity_add_list(&$variables) {
  foreach ($variables['bundles'] as $bundle_name => $bundle_info) {
    $route_name = "entity.assignment.add_page";
    $nid = \Drupal::request()->query->get('node');
    $options = ['absolute' => TRUE];
    $url = Url::fromRoute($route_name);
    $url = Url::fromUserInput($url->toString() . '/' . $bundle_name . '?node=' . $nid, $options);

    $bundle_info['add_link']->setUrl($url);
  }
}
